# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.notifier.query_handler.get_notifications:
        class: Kreta\Notifier\Infrastructure\Application\Query\Elasticsearch\Inbox\ElasticsearchGetNotificationsHandler
        arguments:
            - "@kreta.notifier.repository.inbox_user_read"
        tags:
            -
                name: query_handler
                handles: Kreta\Notifier\Application\Query\Inbox\GetNotificationsQuery
