# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.notifier.event_store.redis_user:
        class: Kreta\SharedKernel\Infrastructure\Persistence\Redis\EventStore\RedisEventStore
        arguments:
            - "@snc_redis.default"
            - "@kreta.notifier.serializer"

    kreta.notifier.event_store.redis_notification:
        class: Kreta\SharedKernel\Infrastructure\Persistence\Redis\EventStore\RedisEventStore
        arguments:
            - "@snc_redis.default"
            - "@kreta.notifier.serializer"
