# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.notifier.http_actions.get_domain_events:
        class: Kreta\Notifier\Infrastructure\Symfony\HttpAction\GetDomainEventsAction
        arguments:
            - "@kreta.notifier.query_bus"

    kreta.notifier.http_actions.view_user_notifications:
        class: Kreta\Notifier\Infrastructure\Symfony\HttpAction\ViewUserNotificationsAction
        arguments:
            - "@security.token_storage"
            - "@kreta.notifier.query_bus"

    kreta.notifier.http_actions.mark_as_read_notification:
        class: Kreta\Notifier\Infrastructure\Symfony\HttpAction\MarkAsReadNotificationAction
        arguments:
            - "@security.token_storage"
            - "@kreta.notifier.command_bus"

    kreta.notifier.http_actions.mark_as_unread_notification:
        class: Kreta\Notifier\Infrastructure\Symfony\HttpAction\MarkAsUnreadNotificationAction
        arguments:
            - "@security.token_storage"
            - "@kreta.notifier.command_bus"

    kreta.notifier.http_actions.mark_all_as_read_notifications:
        class: Kreta\Notifier\Infrastructure\Symfony\HttpAction\MarkAllAsReadNotificationsAction
        arguments:
            - "@security.token_storage"
            - "@kreta.notifier.command_bus"
            - "@kreta.notifier.query_bus"
