# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.notifier.projection.event_handler.user_signed_up:
        class: Kreta\Notifier\Infrastructure\Projection\EventHandler\Elasticsearch\Inbox\ElasticsearchUserSignedUpEventHandler
        arguments:
            - "@kreta.notifier.repository.inbox_user_read"

    kreta.notifier.projection.event_handler.user_received_notification:
        class: Kreta\Notifier\Infrastructure\Projection\EventHandler\Elasticsearch\Inbox\ElasticsearchUserReceivedNotificationEventHandler
        arguments:
            - "@kreta.notifier.repository.inbox_user_read"

    kreta.notifier.projection.event_handler.user_read_notification:
        class: Kreta\Notifier\Infrastructure\Projection\EventHandler\Elasticsearch\Inbox\ElasticsearchUserReadNotificationEventHandler
        arguments:
            - "@kreta.notifier.repository.inbox_user_read"

    kreta.notifier.projection.event_handler.user_unread_notification:
        class: Kreta\Notifier\Infrastructure\Projection\EventHandler\Elasticsearch\Inbox\ElasticsearchUserUnreadNotificationEventHandler
        arguments:
            - "@kreta.notifier.repository.inbox_user_read"
