# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.notifier.query_response.get_domain_events:
        class: Kreta\Notifier\Infrastructure\Application\SymfonyRouterGetDomainEventsResponse
        arguments:
            - "@router"

    kreta.notifier.query_handler.get_domain_events:
        class: Kreta\Notifier\Application\GetDomainEvents
        arguments:
            - "@kreta.notifier.event_store.redis"
            - "@kreta.notifier.query_response.get_domain_events"
        tags:
            -
                name: query_handler
                handles: Kreta\Notifier\Application\GetDomainEventsQuery
