# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    kreta.notifier.elasticsearch.client_builder:
        class: Elasticsearch\ClientBuilder
        public: false

    kreta.notifier.elasticsearch.client:
        class: Elasticsearch\Client
        factory:
            - "@kreta.notifier.elasticsearch.client_builder"
            - fromConfig
        public: false
        arguments:
            -
                hosts:
                    - "%notifier_es_host%"

    kreta.notifier.view.inbox.user:
        class: Kreta\Notifier\Infrastructure\Domain\ReadModel\Inbox\ElasticsearchUserView
        arguments:
            - "@kreta.notifier.elasticsearch.client"
            - "%notifier_es_user_index%"
            - "%notifier_es_user_type%"

    kreta.notifier.view.inbox.notification:
        class: Kreta\Notifier\Infrastructure\Domain\ReadModel\Inbox\Notification\ElasticsearchNotificationView
        arguments:
            - "@kreta.notifier.elasticsearch.client"
            - "%notifier_es_notification_index%"
            - "%notifier_es_notification_type%"

    kreta.notifier.view_specification_factory.inbox.notification:
        class: Kreta\Notifier\Infrastructure\Domain\ReadModel\Inbox\Notification\ElasticsearchNotificationSpecificationFactory
